# Generated by Django 6.1.1 on 2026-09-14 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condominius',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cnpj', models.CharField(max_length=18, validators=[django.core.validators.MinLengthValidator(18)])),
                ('type_condominious', models.CharField(choices=[('Residencial', 'Residencial'), ('Comercial', 'Comercial'), ('Misto', 'Misto')])),
                ('quantity_building', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('cep', models.CharField(max_length=8, validators=[django.core.validators.MinLengthValidator(8)])),
                ('logradouro', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=20)),
                ('complemento', models.CharField(max_length=100, null=True)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('uf', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
            ],
        ),
    ]
