# Generated by Django 6.1.1 on 2026-09-28 01:47

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condominius',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('cnpj', models.CharField(blank=True, max_length=18)),
                ('type_condominious', models.CharField(choices=[('RESIDENCIAL', 'Residencial'), ('COMERCIAL', 'Comercial'), ('MISTO', 'Misto')], default='RESIDENCIAL', max_length=20)),
                ('quantity_building', models.PositiveIntegerField(default=1)),
                ('cep', models.CharField(blank=True, max_length=9)),
                ('logradouro', models.CharField(blank=True, max_length=150)),
                ('numero', models.CharField(blank=True, max_length=20)),
                ('complemento', models.CharField(blank=True, max_length=100)),
                ('bairro', models.CharField(blank=True, max_length=100)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('uf', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'verbose_name': 'Condomínio',
                'verbose_name_plural': 'Condomínios',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Client', 'Client')], default='Client', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Unity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20)),
                ('building', models.CharField(blank=True, max_length=20)),
                ('responsible_name', models.CharField(blank=True, max_length=150)),
                ('status', models.CharField(choices=[('OCUPADO', 'Ocupado'), ('VAGO', 'Vago')], default='VAGO', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='condominiusSystem.condominius')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'ordering': ['condominio', 'building', 'number'],
            },
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competencia', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_vencimento', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('VENCIDO', 'Vencido'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('forma_pagamento', models.CharField(blank=True, choices=[('BOLETO', 'Boleto'), ('PIX', 'Pix'), ('CARTAO', 'Cartão')], max_length=10)),
                ('multa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('juros', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='condominiusSystem.unity')),
            ],
            options={
                'verbose_name': 'Cobrança',
                'verbose_name_plural': 'Cobranças',
                'ordering': ['-competencia', 'unidade'],
            },
        ),
        migrations.CreateModel(
            name='Agreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_parcelas', models.PositiveSmallIntegerField()),
                ('data_primeira_parcela', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('ATIVO', 'Ativo'), ('QUITADO', 'Quitado'), ('CANCELADO', 'Cancelado')], default='ATIVO', max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('cobrancas', models.ManyToManyField(related_name='acordos', to='condominiusSystem.charge')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acordos', to='condominiusSystem.unity')),
            ],
            options={
                'verbose_name': 'Acordo',
                'verbose_name_plural': 'Acordos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='AgreementInstallment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('data_vencimento', models.DateField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago')], default='PENDENTE', max_length=10)),
                ('data_pagamento', models.DateField(blank=True, null=True)),
                ('acordo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='condominiusSystem.agreement')),
            ],
            options={
                'verbose_name': 'Parcela do acordo',
                'verbose_name_plural': 'Parcelas do acordo',
                'ordering': ['acordo', 'numero'],
                'constraints': [models.UniqueConstraint(fields=('acordo', 'numero'), name='unique_installment_number_per_agreement')],
            },
        ),
        migrations.AddConstraint(
            model_name='unity',
            constraint=models.UniqueConstraint(fields=('condominio', 'building', 'number'), name='unique_unity_in_condominium'),
        ),
        migrations.AddConstraint(
            model_name='charge',
            constraint=models.UniqueConstraint(fields=('unidade', 'competencia'), name='unique_charge_per_unit_competence'),
        ),
    ]
