# Generated by Django 6.1.1 on 2026-09-28 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('condominiusSystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='unity',
            name='unique_unity_in_condominium',
        ),
        migrations.AddConstraint(
            model_name='unity',
            constraint=models.UniqueConstraint(condition=models.Q(('building', '')), fields=('condominio', 'number'), name='unique_unit_no_block'),
        ),
        migrations.AddConstraint(
            model_name='unity',
            constraint=models.UniqueConstraint(condition=models.Q(('building', ''), _negated=True), fields=('condominio', 'building', 'number'), name='unique_unit_in_block'),
        ),
    ]
